### ISSUE TITLE
Are the image names in pkl the same as names in AffectNet dataset?

### ISSUE THREAD

**Issue by desti-nation** [face-analysis/emonet#10]
![image](https://user-images.githubusercontent.com/22908510/159148934-764fa566-32c3-4a94-b6f0-4648822fa52f.png)

**Comment by OlliMark** [comment]
Did you find out how these filenames represent the Images in AffectNet?

**Comment by JeanKossaifi** [comment]
They are.

**Comment by OlliMark** [comment]
As far as I see it, the filenames in the validation dataset are just .jpg-files, that are consecutively numbered. Whereas the filenames in the pickled files are a combination of numbers and letters. 

I am currently working with the small 4GB AffectNet dataset. Are the file names in the pickled file referring to the large AffectNet Dataset?
