### ISSUE TITLE
8 classes are not clear

### ISSUE THREAD

**Issue by GowthamGithubrepo** [face-analysis/emonet#5]
can I know what each class number signifies. It is unclear from the repo code as what that expression is

**Comment by antoinetlc** [comment]
Hello,

Sorry I forgot to add it in the readme.
The mapping from class number to expression is as follows.

For 8 emotions :

0 - Neutral
1 - Happy
2 - Sad
3 - Surprise
4 - Fear
5 - Disgust
6 - Anger
7 - Contempt

For 5 emotions :

0 - Neutral
1 - Happy
2 - Sad
3 - Surprise
4 - Fear

**Comment by JeanKossaifi** [comment]
It's also specified in the DataLoader: https://github.com/face-analysis/emonet/blob/47006243857718250907eed4c9b3c39e1578c955/emonet/data/affecnet.py#L10
